// Copyright 2024 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51
//
// Description: Automatically generated Mempool NoC routing table
//
// Generated by hardware/scripts/gen_routing_table.py

package routing_table_pkg;

import mempool_pkg::*;
import floo_pkg::*;

typedef logic [4:0] routing_rule_addr_t;

typedef struct packed {
  logic [2:0]  idx;
  routing_rule_addr_t  start_addr;
  routing_rule_addr_t  end_addr;
} routing_rule_t;

localparam routing_rule_t [3:0][3:0][15:0] RoutingTables = {
  {
    {
      { East, 5'd0, 5'd2 },
      { East, 5'd2, 5'd4 },
      { East, 5'd4, 5'd6 },
      { East, 5'd6, 5'd8 },
      { West, 5'd8, 5'd10 },
      { West, 5'd10, 5'd12 },
      { West, 5'd12, 5'd14 },
      { West, 5'd14, 5'd16 },
      { West, 5'd16, 5'd18 },
      { West, 5'd18, 5'd20 },
      { West, 5'd20, 5'd22 },
      { West, 5'd22, 5'd24 },
      { North, 5'd24, 5'd26 },
      { South, 5'd26, 5'd28 },
      { South, 5'd28, 5'd30 },
      { Eject, 5'd30, 5'd0 }
    },
    {
      { East, 5'd0, 5'd2 },
      { East, 5'd2, 5'd4 },
      { East, 5'd4, 5'd6 },
      { East, 5'd6, 5'd8 },
      { West, 5'd8, 5'd10 },
      { West, 5'd10, 5'd12 },
      { West, 5'd12, 5'd14 },
      { West, 5'd14, 5'd16 },
      { West, 5'd16, 5'd18 },
      { West, 5'd18, 5'd20 },
      { West, 5'd20, 5'd22 },
      { West, 5'd22, 5'd24 },
      { North, 5'd24, 5'd26 },
      { South, 5'd26, 5'd28 },
      { Eject, 5'd28, 5'd30 },
      { North, 5'd30, 5'd0 }
    },
    {
      { East, 5'd0, 5'd2 },
      { East, 5'd2, 5'd4 },
      { East, 5'd4, 5'd6 },
      { East, 5'd6, 5'd8 },
      { West, 5'd8, 5'd10 },
      { West, 5'd10, 5'd12 },
      { West, 5'd12, 5'd14 },
      { West, 5'd14, 5'd16 },
      { West, 5'd16, 5'd18 },
      { West, 5'd18, 5'd20 },
      { West, 5'd20, 5'd22 },
      { West, 5'd22, 5'd24 },
      { South, 5'd24, 5'd26 },
      { Eject, 5'd26, 5'd28 },
      { North, 5'd28, 5'd30 },
      { South, 5'd30, 5'd0 }
    },
    {
      { East, 5'd0, 5'd2 },
      { East, 5'd2, 5'd4 },
      { East, 5'd4, 5'd6 },
      { East, 5'd6, 5'd8 },
      { West, 5'd8, 5'd10 },
      { West, 5'd10, 5'd12 },
      { West, 5'd12, 5'd14 },
      { West, 5'd14, 5'd16 },
      { West, 5'd16, 5'd18 },
      { West, 5'd18, 5'd20 },
      { West, 5'd20, 5'd22 },
      { West, 5'd22, 5'd24 },
      { Eject, 5'd24, 5'd26 },
      { North, 5'd26, 5'd28 },
      { North, 5'd28, 5'd30 },
      { South, 5'd30, 5'd0 }
    }
  },
  {
    {
      { East, 5'd0, 5'd2 },
      { East, 5'd2, 5'd4 },
      { East, 5'd4, 5'd6 },
      { East, 5'd6, 5'd8 },
      { West, 5'd8, 5'd10 },
      { West, 5'd10, 5'd12 },
      { West, 5'd12, 5'd14 },
      { West, 5'd14, 5'd16 },
      { North, 5'd16, 5'd18 },
      { South, 5'd18, 5'd20 },
      { South, 5'd20, 5'd22 },
      { Eject, 5'd22, 5'd24 },
      { East, 5'd24, 5'd26 },
      { East, 5'd26, 5'd28 },
      { East, 5'd28, 5'd30 },
      { East, 5'd30, 5'd0 }
    },
    {
      { East, 5'd0, 5'd2 },
      { East, 5'd2, 5'd4 },
      { East, 5'd4, 5'd6 },
      { East, 5'd6, 5'd8 },
      { West, 5'd8, 5'd10 },
      { West, 5'd10, 5'd12 },
      { West, 5'd12, 5'd14 },
      { West, 5'd14, 5'd16 },
      { North, 5'd16, 5'd18 },
      { South, 5'd18, 5'd20 },
      { Eject, 5'd20, 5'd22 },
      { North, 5'd22, 5'd24 },
      { East, 5'd24, 5'd26 },
      { East, 5'd26, 5'd28 },
      { East, 5'd28, 5'd30 },
      { East, 5'd30, 5'd0 }
    },
    {
      { East, 5'd0, 5'd2 },
      { East, 5'd2, 5'd4 },
      { East, 5'd4, 5'd6 },
      { East, 5'd6, 5'd8 },
      { West, 5'd8, 5'd10 },
      { West, 5'd10, 5'd12 },
      { West, 5'd12, 5'd14 },
      { West, 5'd14, 5'd16 },
      { South, 5'd16, 5'd18 },
      { Eject, 5'd18, 5'd20 },
      { North, 5'd20, 5'd22 },
      { South, 5'd22, 5'd24 },
      { East, 5'd24, 5'd26 },
      { East, 5'd26, 5'd28 },
      { East, 5'd28, 5'd30 },
      { East, 5'd30, 5'd0 }
    },
    {
      { East, 5'd0, 5'd2 },
      { East, 5'd2, 5'd4 },
      { East, 5'd4, 5'd6 },
      { East, 5'd6, 5'd8 },
      { West, 5'd8, 5'd10 },
      { West, 5'd10, 5'd12 },
      { West, 5'd12, 5'd14 },
      { West, 5'd14, 5'd16 },
      { Eject, 5'd16, 5'd18 },
      { North, 5'd18, 5'd20 },
      { North, 5'd20, 5'd22 },
      { South, 5'd22, 5'd24 },
      { East, 5'd24, 5'd26 },
      { East, 5'd26, 5'd28 },
      { East, 5'd28, 5'd30 },
      { East, 5'd30, 5'd0 }
    }
  },
  {
    {
      { West, 5'd0, 5'd2 },
      { West, 5'd2, 5'd4 },
      { West, 5'd4, 5'd6 },
      { West, 5'd6, 5'd8 },
      { North, 5'd8, 5'd10 },
      { South, 5'd10, 5'd12 },
      { South, 5'd12, 5'd14 },
      { Eject, 5'd14, 5'd16 },
      { East, 5'd16, 5'd18 },
      { East, 5'd18, 5'd20 },
      { East, 5'd20, 5'd22 },
      { East, 5'd22, 5'd24 },
      { West, 5'd24, 5'd26 },
      { West, 5'd26, 5'd28 },
      { West, 5'd28, 5'd30 },
      { West, 5'd30, 5'd0 }
    },
    {
      { West, 5'd0, 5'd2 },
      { West, 5'd2, 5'd4 },
      { West, 5'd4, 5'd6 },
      { West, 5'd6, 5'd8 },
      { North, 5'd8, 5'd10 },
      { South, 5'd10, 5'd12 },
      { Eject, 5'd12, 5'd14 },
      { North, 5'd14, 5'd16 },
      { East, 5'd16, 5'd18 },
      { East, 5'd18, 5'd20 },
      { East, 5'd20, 5'd22 },
      { East, 5'd22, 5'd24 },
      { West, 5'd24, 5'd26 },
      { West, 5'd26, 5'd28 },
      { West, 5'd28, 5'd30 },
      { West, 5'd30, 5'd0 }
    },
    {
      { West, 5'd0, 5'd2 },
      { West, 5'd2, 5'd4 },
      { West, 5'd4, 5'd6 },
      { West, 5'd6, 5'd8 },
      { South, 5'd8, 5'd10 },
      { Eject, 5'd10, 5'd12 },
      { North, 5'd12, 5'd14 },
      { South, 5'd14, 5'd16 },
      { East, 5'd16, 5'd18 },
      { East, 5'd18, 5'd20 },
      { East, 5'd20, 5'd22 },
      { East, 5'd22, 5'd24 },
      { West, 5'd24, 5'd26 },
      { West, 5'd26, 5'd28 },
      { West, 5'd28, 5'd30 },
      { West, 5'd30, 5'd0 }
    },
    {
      { West, 5'd0, 5'd2 },
      { West, 5'd2, 5'd4 },
      { West, 5'd4, 5'd6 },
      { West, 5'd6, 5'd8 },
      { Eject, 5'd8, 5'd10 },
      { North, 5'd10, 5'd12 },
      { North, 5'd12, 5'd14 },
      { South, 5'd14, 5'd16 },
      { East, 5'd16, 5'd18 },
      { East, 5'd18, 5'd20 },
      { East, 5'd20, 5'd22 },
      { East, 5'd22, 5'd24 },
      { West, 5'd24, 5'd26 },
      { West, 5'd26, 5'd28 },
      { West, 5'd28, 5'd30 },
      { West, 5'd30, 5'd0 }
    }
  },
  {
    {
      { North, 5'd0, 5'd2 },
      { South, 5'd2, 5'd4 },
      { South, 5'd4, 5'd6 },
      { Eject, 5'd6, 5'd8 },
      { East, 5'd8, 5'd10 },
      { East, 5'd10, 5'd12 },
      { East, 5'd12, 5'd14 },
      { East, 5'd14, 5'd16 },
      { East, 5'd16, 5'd18 },
      { East, 5'd18, 5'd20 },
      { East, 5'd20, 5'd22 },
      { East, 5'd22, 5'd24 },
      { West, 5'd24, 5'd26 },
      { West, 5'd26, 5'd28 },
      { West, 5'd28, 5'd30 },
      { West, 5'd30, 5'd0 }
    },
    {
      { North, 5'd0, 5'd2 },
      { South, 5'd2, 5'd4 },
      { Eject, 5'd4, 5'd6 },
      { North, 5'd6, 5'd8 },
      { East, 5'd8, 5'd10 },
      { East, 5'd10, 5'd12 },
      { East, 5'd12, 5'd14 },
      { East, 5'd14, 5'd16 },
      { East, 5'd16, 5'd18 },
      { East, 5'd18, 5'd20 },
      { East, 5'd20, 5'd22 },
      { East, 5'd22, 5'd24 },
      { West, 5'd24, 5'd26 },
      { West, 5'd26, 5'd28 },
      { West, 5'd28, 5'd30 },
      { West, 5'd30, 5'd0 }
    },
    {
      { South, 5'd0, 5'd2 },
      { Eject, 5'd2, 5'd4 },
      { North, 5'd4, 5'd6 },
      { South, 5'd6, 5'd8 },
      { East, 5'd8, 5'd10 },
      { East, 5'd10, 5'd12 },
      { East, 5'd12, 5'd14 },
      { East, 5'd14, 5'd16 },
      { East, 5'd16, 5'd18 },
      { East, 5'd18, 5'd20 },
      { East, 5'd20, 5'd22 },
      { East, 5'd22, 5'd24 },
      { West, 5'd24, 5'd26 },
      { West, 5'd26, 5'd28 },
      { West, 5'd28, 5'd30 },
      { West, 5'd30, 5'd0 }
    },
    {
      { Eject, 5'd0, 5'd2 },
      { North, 5'd2, 5'd4 },
      { North, 5'd4, 5'd6 },
      { South, 5'd6, 5'd8 },
      { East, 5'd8, 5'd10 },
      { East, 5'd10, 5'd12 },
      { East, 5'd12, 5'd14 },
      { East, 5'd14, 5'd16 },
      { East, 5'd16, 5'd18 },
      { East, 5'd18, 5'd20 },
      { East, 5'd20, 5'd22 },
      { East, 5'd22, 5'd24 },
      { West, 5'd24, 5'd26 },
      { West, 5'd26, 5'd28 },
      { West, 5'd28, 5'd30 },
      { West, 5'd30, 5'd0 }
    }
  }
};

endpackage
