// Copyright 2024 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51
//
// Description: Automatically generated Mempool NoC routing table
//
// Generated by hardware/scripts/gen_routing_table.py

package routing_table_pkg;

import mempool_pkg::*;
import floo_pkg::*;

typedef struct packed {
  logic [2:0]  idx;
  logic [3:0]  start_addr;
  logic [3:0]  end_addr;
} routing_rule_t;

routing_rule_t [0:3][0:3][0:15] RoutingTables = {
  {
    {
      { Eject, 4'd0, 4'd1 },
      { North, 4'd1, 4'd2 },
      { North, 4'd2, 4'd3 },
      { South, 4'd3, 4'd4 },
      { East, 4'd4, 4'd5 },
      { East, 4'd5, 4'd6 },
      { East, 4'd6, 4'd7 },
      { East, 4'd7, 4'd8 },
      { East, 4'd8, 4'd9 },
      { East, 4'd9, 4'd10 },
      { East, 4'd10, 4'd11 },
      { East, 4'd11, 4'd12 },
      { West, 4'd12, 4'd13 },
      { West, 4'd13, 4'd14 },
      { West, 4'd14, 4'd15 },
      { West, 4'd15, 4'd0 }
    },
    {
      { South, 4'd0, 4'd1 },
      { Eject, 4'd1, 4'd2 },
      { North, 4'd2, 4'd3 },
      { South, 4'd3, 4'd4 },
      { East, 4'd4, 4'd5 },
      { East, 4'd5, 4'd6 },
      { East, 4'd6, 4'd7 },
      { East, 4'd7, 4'd8 },
      { East, 4'd8, 4'd9 },
      { East, 4'd9, 4'd10 },
      { East, 4'd10, 4'd11 },
      { East, 4'd11, 4'd12 },
      { West, 4'd12, 4'd13 },
      { West, 4'd13, 4'd14 },
      { West, 4'd14, 4'd15 },
      { West, 4'd15, 4'd0 }
    },
    {
      { North, 4'd0, 4'd1 },
      { South, 4'd1, 4'd2 },
      { Eject, 4'd2, 4'd3 },
      { North, 4'd3, 4'd4 },
      { East, 4'd4, 4'd5 },
      { East, 4'd5, 4'd6 },
      { East, 4'd6, 4'd7 },
      { East, 4'd7, 4'd8 },
      { East, 4'd8, 4'd9 },
      { East, 4'd9, 4'd10 },
      { East, 4'd10, 4'd11 },
      { East, 4'd11, 4'd12 },
      { West, 4'd12, 4'd13 },
      { West, 4'd13, 4'd14 },
      { West, 4'd14, 4'd15 },
      { West, 4'd15, 4'd0 }
    },
    {
      { North, 4'd0, 4'd1 },
      { South, 4'd1, 4'd2 },
      { South, 4'd2, 4'd3 },
      { Eject, 4'd3, 4'd4 },
      { East, 4'd4, 4'd5 },
      { East, 4'd5, 4'd6 },
      { East, 4'd6, 4'd7 },
      { East, 4'd7, 4'd8 },
      { East, 4'd8, 4'd9 },
      { East, 4'd9, 4'd10 },
      { East, 4'd10, 4'd11 },
      { East, 4'd11, 4'd12 },
      { West, 4'd12, 4'd13 },
      { West, 4'd13, 4'd14 },
      { West, 4'd14, 4'd15 },
      { West, 4'd15, 4'd0 }
    }
  },
  {
    {
      { West, 4'd0, 4'd1 },
      { West, 4'd1, 4'd2 },
      { West, 4'd2, 4'd3 },
      { West, 4'd3, 4'd4 },
      { Eject, 4'd4, 4'd5 },
      { North, 4'd5, 4'd6 },
      { North, 4'd6, 4'd7 },
      { South, 4'd7, 4'd8 },
      { East, 4'd8, 4'd9 },
      { East, 4'd9, 4'd10 },
      { East, 4'd10, 4'd11 },
      { East, 4'd11, 4'd12 },
      { West, 4'd12, 4'd13 },
      { West, 4'd13, 4'd14 },
      { West, 4'd14, 4'd15 },
      { West, 4'd15, 4'd0 }
    },
    {
      { West, 4'd0, 4'd1 },
      { West, 4'd1, 4'd2 },
      { West, 4'd2, 4'd3 },
      { West, 4'd3, 4'd4 },
      { South, 4'd4, 4'd5 },
      { Eject, 4'd5, 4'd6 },
      { North, 4'd6, 4'd7 },
      { South, 4'd7, 4'd8 },
      { East, 4'd8, 4'd9 },
      { East, 4'd9, 4'd10 },
      { East, 4'd10, 4'd11 },
      { East, 4'd11, 4'd12 },
      { West, 4'd12, 4'd13 },
      { West, 4'd13, 4'd14 },
      { West, 4'd14, 4'd15 },
      { West, 4'd15, 4'd0 }
    },
    {
      { West, 4'd0, 4'd1 },
      { West, 4'd1, 4'd2 },
      { West, 4'd2, 4'd3 },
      { West, 4'd3, 4'd4 },
      { North, 4'd4, 4'd5 },
      { South, 4'd5, 4'd6 },
      { Eject, 4'd6, 4'd7 },
      { North, 4'd7, 4'd8 },
      { East, 4'd8, 4'd9 },
      { East, 4'd9, 4'd10 },
      { East, 4'd10, 4'd11 },
      { East, 4'd11, 4'd12 },
      { West, 4'd12, 4'd13 },
      { West, 4'd13, 4'd14 },
      { West, 4'd14, 4'd15 },
      { West, 4'd15, 4'd0 }
    },
    {
      { West, 4'd0, 4'd1 },
      { West, 4'd1, 4'd2 },
      { West, 4'd2, 4'd3 },
      { West, 4'd3, 4'd4 },
      { North, 4'd4, 4'd5 },
      { South, 4'd5, 4'd6 },
      { South, 4'd6, 4'd7 },
      { Eject, 4'd7, 4'd8 },
      { East, 4'd8, 4'd9 },
      { East, 4'd9, 4'd10 },
      { East, 4'd10, 4'd11 },
      { East, 4'd11, 4'd12 },
      { West, 4'd12, 4'd13 },
      { West, 4'd13, 4'd14 },
      { West, 4'd14, 4'd15 },
      { West, 4'd15, 4'd0 }
    }
  },
  {
    {
      { East, 4'd0, 4'd1 },
      { East, 4'd1, 4'd2 },
      { East, 4'd2, 4'd3 },
      { East, 4'd3, 4'd4 },
      { West, 4'd4, 4'd5 },
      { West, 4'd5, 4'd6 },
      { West, 4'd6, 4'd7 },
      { West, 4'd7, 4'd8 },
      { Eject, 4'd8, 4'd9 },
      { North, 4'd9, 4'd10 },
      { North, 4'd10, 4'd11 },
      { South, 4'd11, 4'd12 },
      { East, 4'd12, 4'd13 },
      { East, 4'd13, 4'd14 },
      { East, 4'd14, 4'd15 },
      { East, 4'd15, 4'd0 }
    },
    {
      { East, 4'd0, 4'd1 },
      { East, 4'd1, 4'd2 },
      { East, 4'd2, 4'd3 },
      { East, 4'd3, 4'd4 },
      { West, 4'd4, 4'd5 },
      { West, 4'd5, 4'd6 },
      { West, 4'd6, 4'd7 },
      { West, 4'd7, 4'd8 },
      { South, 4'd8, 4'd9 },
      { Eject, 4'd9, 4'd10 },
      { North, 4'd10, 4'd11 },
      { South, 4'd11, 4'd12 },
      { East, 4'd12, 4'd13 },
      { East, 4'd13, 4'd14 },
      { East, 4'd14, 4'd15 },
      { East, 4'd15, 4'd0 }
    },
    {
      { East, 4'd0, 4'd1 },
      { East, 4'd1, 4'd2 },
      { East, 4'd2, 4'd3 },
      { East, 4'd3, 4'd4 },
      { West, 4'd4, 4'd5 },
      { West, 4'd5, 4'd6 },
      { West, 4'd6, 4'd7 },
      { West, 4'd7, 4'd8 },
      { North, 4'd8, 4'd9 },
      { South, 4'd9, 4'd10 },
      { Eject, 4'd10, 4'd11 },
      { North, 4'd11, 4'd12 },
      { East, 4'd12, 4'd13 },
      { East, 4'd13, 4'd14 },
      { East, 4'd14, 4'd15 },
      { East, 4'd15, 4'd0 }
    },
    {
      { East, 4'd0, 4'd1 },
      { East, 4'd1, 4'd2 },
      { East, 4'd2, 4'd3 },
      { East, 4'd3, 4'd4 },
      { West, 4'd4, 4'd5 },
      { West, 4'd5, 4'd6 },
      { West, 4'd6, 4'd7 },
      { West, 4'd7, 4'd8 },
      { North, 4'd8, 4'd9 },
      { South, 4'd9, 4'd10 },
      { South, 4'd10, 4'd11 },
      { Eject, 4'd11, 4'd12 },
      { East, 4'd12, 4'd13 },
      { East, 4'd13, 4'd14 },
      { East, 4'd14, 4'd15 },
      { East, 4'd15, 4'd0 }
    }
  },
  {
    {
      { East, 4'd0, 4'd1 },
      { East, 4'd1, 4'd2 },
      { East, 4'd2, 4'd3 },
      { East, 4'd3, 4'd4 },
      { West, 4'd4, 4'd5 },
      { West, 4'd5, 4'd6 },
      { West, 4'd6, 4'd7 },
      { West, 4'd7, 4'd8 },
      { West, 4'd8, 4'd9 },
      { West, 4'd9, 4'd10 },
      { West, 4'd10, 4'd11 },
      { West, 4'd11, 4'd12 },
      { Eject, 4'd12, 4'd13 },
      { North, 4'd13, 4'd14 },
      { North, 4'd14, 4'd15 },
      { South, 4'd15, 4'd0 }
    },
    {
      { East, 4'd0, 4'd1 },
      { East, 4'd1, 4'd2 },
      { East, 4'd2, 4'd3 },
      { East, 4'd3, 4'd4 },
      { West, 4'd4, 4'd5 },
      { West, 4'd5, 4'd6 },
      { West, 4'd6, 4'd7 },
      { West, 4'd7, 4'd8 },
      { West, 4'd8, 4'd9 },
      { West, 4'd9, 4'd10 },
      { West, 4'd10, 4'd11 },
      { West, 4'd11, 4'd12 },
      { South, 4'd12, 4'd13 },
      { Eject, 4'd13, 4'd14 },
      { North, 4'd14, 4'd15 },
      { South, 4'd15, 4'd0 }
    },
    {
      { East, 4'd0, 4'd1 },
      { East, 4'd1, 4'd2 },
      { East, 4'd2, 4'd3 },
      { East, 4'd3, 4'd4 },
      { West, 4'd4, 4'd5 },
      { West, 4'd5, 4'd6 },
      { West, 4'd6, 4'd7 },
      { West, 4'd7, 4'd8 },
      { West, 4'd8, 4'd9 },
      { West, 4'd9, 4'd10 },
      { West, 4'd10, 4'd11 },
      { West, 4'd11, 4'd12 },
      { North, 4'd12, 4'd13 },
      { South, 4'd13, 4'd14 },
      { Eject, 4'd14, 4'd15 },
      { North, 4'd15, 4'd0 }
    },
    {
      { East, 4'd0, 4'd1 },
      { East, 4'd1, 4'd2 },
      { East, 4'd2, 4'd3 },
      { East, 4'd3, 4'd4 },
      { West, 4'd4, 4'd5 },
      { West, 4'd5, 4'd6 },
      { West, 4'd6, 4'd7 },
      { West, 4'd7, 4'd8 },
      { West, 4'd8, 4'd9 },
      { West, 4'd9, 4'd10 },
      { West, 4'd10, 4'd11 },
      { West, 4'd11, 4'd12 },
      { North, 4'd12, 4'd13 },
      { South, 4'd13, 4'd14 },
      { South, 4'd14, 4'd15 },
      { Eject, 4'd15, 4'd0 }
    }
  }
};

endpackage
