// Copyright 2022 ETH Zurich and University of Bologna.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// Automatically generated by:
// data/data_chest_q16.py

\
<% def array_to_cstr(array):
    out = '{'
    i = 0
    out += '\n'
    for a in array:
        out += '(__fp16){:.5}f, '.format(a)
        i += 1
        if i % 8 == 0:
            out += '\n'
    out = out[:-2] + '}'
    return out
%> \

#define N_TX (${nb_tx})
#define N_RX (${nb_rx})
#define N_SAMPLES (${nb_samples})

__fp16 l2_PilotRX[${2*nb_rx*nb_samples}] = ${array_to_cstr(pilot_rx)};

__fp16 l2_PilotTX[${2*nb_tx*nb_samples}] = ${array_to_cstr(pilot_tx)};

__fp16 l2_HEST[${2*nb_rx*nb_tx*nb_samples}] = ${array_to_cstr(Hest)};
