# Copyright 2021 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Create group for core $3 from group $1 tile $2 (core_id=NUM_CORES_PER_group*$1+NUM_CORES_PER_TILE*$2+$3)
if {$config == {terapool}} {
  set path "/mempool_tb/dut/gen_clusters[$1]/i_mempool_cluster/gen_groups[$2]/gen_rtl_group/i_group/gen_sub_groups[$3]/gen_rtl_sg/i_sub_group/gen_tiles[$4]/i_tile/gen_cores[$5]/gen_mempool_cc/riscv_core"
  set group "-group cluster_[$1] -group group_[$2] -group sub_group_[$3] -group tile_[$4] -group core_[$5]"
  set WhyDoesModelsimSpamTheLastVariableIDefine ""
} else {
  set prefix "/mempool_tb/dut/gen_clusters[$1]/i_mempool_cluster/gen_groups[$2]/i_group/gen_tiles[$3]/i_tile/gen_cores[$4]/gen_mempool_cc/riscv_core"
  set groups "-group cluster_[$1] -group group_[$2] -group tile_[$3] -group core_[$4]"
  set WhyDoesModelsimSpamTheLastVariableIDefine ""
}

{*}"add wave -noupdate $groups -group Params $prefix/BootAddr"
{*}"add wave -noupdate $groups -group Params $prefix/MTVEC"
{*}"add wave -noupdate $groups -group Params $prefix/RVE"
{*}"add wave -noupdate $groups -group Params $prefix/RVM"
{*}"add wave -noupdate $groups -group Params $prefix/RegisterOffloadReq"
{*}"add wave -noupdate $groups -group Params $prefix/RegisterOffloadResp"
{*}"add wave -noupdate $groups -group Params $prefix/RegisterTCDMReq"
{*}"add wave -noupdate $groups -group Params $prefix/RegisterTCDMResp"
{*}"add wave -noupdate $groups $prefix/i_snitch/clk_i"
{*}"add wave -noupdate $groups $prefix/i_snitch/rst_i"
{*}"add wave -noupdate $groups -radix unsigned $prefix/i_snitch/hart_id_i"

{*}"add wave -noupdate $groups -divider Instructions"
{*}"add wave -noupdate $groups $prefix/i_snitch/inst_addr_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/inst_data_i"
{*}"add wave -noupdate $groups $prefix/i_snitch/inst_valid_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/inst_ready_i"

{*}"add wave -noupdate $groups -divider Load/Store"
{*}"add wave -noupdate $groups $prefix/i_snitch/data_qaddr_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/data_qwrite_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/data_qamo_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/data_qdata_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/data_qstrb_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/data_qvalid_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/data_qready_i"
{*}"add wave -noupdate $groups $prefix/i_snitch/data_pdata_i"
{*}"add wave -noupdate $groups $prefix/i_snitch/data_perror_i"
{*}"add wave -noupdate $groups $prefix/i_snitch/data_pvalid_i"
{*}"add wave -noupdate $groups $prefix/i_snitch/data_pready_o"

{*}"add wave -noupdate $groups -divider FPSS"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/acc_req_valid_i"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/acc_req_ready_o"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/acc_resp_valid_o"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/acc_resp_ready_i"

{*}"add wave -noupdate $groups -divider FPU"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/operands_i"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/rnd_mode_i"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/op_i"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/op_mod_i"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/src_fmt_i"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/dst_fmt_i"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/int_fmt_i"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/vectorial_op_i"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/tag_i"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/in_valid_i"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/in_ready_o"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/result_o"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/status_o"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/tag_o"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/out_valid_o"
{*}"add wave -noupdate $groups $prefix/gen_fpu/i_snitch_fp_ss/i_fpu/out_ready_i"

{*}"add wave -noupdate $groups -divider Accelerator"
{*}"add wave -noupdate $groups $prefix/i_snitch/acc_qaddr_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/acc_qid_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/acc_qdata_op_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/acc_qdata_arga_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/acc_qdata_argb_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/acc_qdata_argc_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/acc_qvalid_o"
{*}"add wave -noupdate $groups $prefix/i_snitch/acc_qready_i"
{*}"add wave -noupdate $groups $prefix/i_snitch/acc_pdata_i"
{*}"add wave -noupdate $groups $prefix/i_snitch/acc_pid_i"
{*}"add wave -noupdate $groups $prefix/i_snitch/acc_perror_i"
{*}"add wave -noupdate $groups $prefix/i_snitch/acc_pvalid_i"
{*}"add wave -noupdate $groups $prefix/i_snitch/acc_pready_o"

{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/illegal_inst"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/stall"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/lsu_stall"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/acc_stall"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/zero_lsb"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/pc_d"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/pc_q"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/wfi_d"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/wfi_q"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/wake_up_sync_i"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/wake_up_d"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/wake_up_q"

{*}"add wave -noupdate $groups -group Internal -divider LSU"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/ls_size"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/ls_amo"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/ld_result"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/lsu_qready"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/lsu_qvalid"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/lsu_pvalid"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/lsu_pready"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/lsu_rd"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/retire_load"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/retire_i"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/retire_acc"

{*}"add wave -noupdate $groups -group Internal -divider Register"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/i_snitch_regfile/raddr_i"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/i_snitch_regfile/waddr_i"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/i_snitch_regfile/wdata_i"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/i_snitch_regfile/we_i"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/i_snitch_regfile/rdata_o"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/i_snitch_regfile/mem"

{*}"add wave -noupdate $groups -group Internal -divider ALU"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/opa"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/opb"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/iimm"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/uimm"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/jimm"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/bimm"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/simm"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/adder_result"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/alu_result"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/rd"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/rs1"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/rs2"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/gpr_raddr"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/gpr_rdata"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/gpr_waddr"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/gpr_wdata"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/gpr_we"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/consec_pc"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/sb_d"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/sb_q"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/is_load"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/is_store"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/is_signed"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/is_fp_load"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/is_fp_store"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/ls_misaligned"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/ld_addr_misaligned"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/st_addr_misaligned"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/valid_instr"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/exception"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/alu_op"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/opa_select"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/opb_select"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/write_rd"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/uses_rd"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/next_pc"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/rd_select"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/rd_bypass"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/is_branch"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/csr_rvalue"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/csr_en"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/cycle_q"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/instret_q"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/acc_register_rd"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/operands_ready"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/dst_ready"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/opa_ready"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/opb_ready"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/shift_opa"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/shift_opa_reversed"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/shift_right_result"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/shift_left_result"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/shift_opa_ext"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/shift_right_result_ext"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/shift_left"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/shift_arithmetic"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/alu_opa"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/alu_opb"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/alu_writeback"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/csr_trace_q"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/csr_trace_en"
{*}"add wave -noupdate $groups -group Internal $prefix/i_snitch/core_events_o"
